## Dev-only utility: NOT part of the package. Parses the existing
## roxygen-style comments in R/*.R and generates NAMESPACE + man/*.Rd
## by hand, since roxygen2 can't be installed in this sandbox (no
## CRAN access). This mirrors what `devtools::document()` would
## produce, restricted to what our comment format actually uses:
## title, param, return, export.

r_dir <- "R"
man_dir <- "man"
dir.create(man_dir, showWarnings = FALSE)

files <- list.files(r_dir, pattern = "\\.R$", full.names = TRUE)

escape_rd <- function(x) {
  x <- gsub("\\\\", "\\\\\\\\", x)
  x <- gsub("%", "\\\\%", x)
  x
}

parse_file <- function(path) {
  lines <- readLines(path, warn = FALSE)
  n <- length(lines)
  results <- list()
  i <- 1
  while (i <= n) {
    if (grepl("^#'", lines[i])) {
      block_start <- i
      while (i <= n && grepl("^#'", lines[i])) i <- i + 1
      block_end <- i - 1
      # the function definition should be on the very next non-blank line
      if (i <= n && grepl("<-\\s*function", lines[i])) {
        fn_line <- lines[i]
        fn_name <- sub("^([A-Za-z_.][A-Za-z0-9_.]*)\\s*<-\\s*function.*$", "\\1", fn_line)
        block <- sub("^#'\\s?", "", lines[block_start:block_end])

        is_export <- any(grepl("^@export", trimws(block)))
        is_internal <- any(grepl("^@keywords internal", trimws(block)))

        # split into title/description (pre-tag) and tagged sections
        tag_idx <- which(grepl("^@", trimws(block)))
        pre <- if (length(tag_idx) > 0) block[seq_len(min(tag_idx) - 1)] else block
        pre <- pre[pre != ""]
        title <- if (length(pre) >= 1) pre[1] else fn_name
        description <- if (length(pre) >= 2) paste(pre[-1], collapse = " ") else title

        params <- list()
        return_txt <- NULL
        if (length(tag_idx) > 0) {
          tags <- trimws(block[tag_idx])
          tag_ends <- c(tag_idx[-1] - 1, length(block))
          for (k in seq_along(tag_idx)) {
            seg <- trimws(block[tag_idx[k]:tag_ends[k]])
            seg <- seg[seg != ""]
            first <- seg[1]
            rest <- if (length(seg) > 1) paste(seg[-1], collapse = " ") else ""
            if (grepl("^@param", first)) {
              m <- regmatches(first, regexec("^@param\\s+(\\S+)\\s*(.*)$", first))[[1]]
              if (length(m) == 3) {
                params[[m[2]]] <- trimws(paste(m[3], rest))
              }
            } else if (grepl("^@return", first)) {
              return_txt <- trimws(paste(sub("^@return\\s*", "", first), rest))
            }
          }
        }

        results[[length(results) + 1]] <- list(
          name = fn_name, title = title, description = description,
          params = params, return_txt = return_txt,
          export = is_export, internal = is_internal
        )
      }
    } else {
      i <- i + 1
    }
  }
  results
}

all_fns <- list()
for (f in files) {
  parsed <- parse_file(f)
  for (p in parsed) all_fns[[p$name]] <- p
}

exported <- Filter(function(x) isTRUE(x$export), all_fns)

# ---- NAMESPACE ----
ns_lines <- c(
  "# Generated by hand (dev/generate_docs.R) -- roxygen2 unavailable in this environment.",
  sprintf("export(%s)", sort(names(exported))),
  "import(grDevices)",
  "import(graphics)",
  "importFrom(utils, read.csv, write.csv)"
)
writeLines(ns_lines, "NAMESPACE")

# ---- man/*.Rd ----
for (fn in exported) {
  rd_path <- file.path(man_dir, paste0(fn$name, ".Rd"))
  usage_args <- if (length(fn$params) > 0) paste(names(fn$params), collapse = ", ") else ""
  arg_items <- if (length(fn$params) > 0) {
    paste(sprintf("\\item{%s}{%s}", names(fn$params), vapply(fn$params, escape_rd, character(1))), collapse = "\n")
  } else ""

  rd <- c(
    sprintf("\\name{%s}", fn$name),
    sprintf("\\alias{%s}", fn$name),
    sprintf("\\title{%s}", escape_rd(fn$title)),
    "\\usage{",
    sprintf("%s(%s)", fn$name, usage_args),
    "}",
    if (length(fn$params) > 0) c("\\arguments{", arg_items, "}") else NULL,
    if (!is.null(fn$return_txt)) c("\\value{", escape_rd(fn$return_txt), "}") else NULL,
    "\\description{",
    escape_rd(fn$description),
    "}"
  )
  writeLines(rd, rd_path)
}

cat(sprintf("Wrote NAMESPACE with %d exports and %d .Rd files\n", length(exported), length(exported)))
