test_that("generate_csv_template writes a valid CSV with example rows", {
  tmp <- tempfile(fileext = ".csv")
  generate_csv_template(tmp)
  expect_true(file.exists(tmp))

  df <- utils::read.csv(tmp, stringsAsFactors = FALSE)
  expect_setequal(names(df), c("source", "item", "provider", "region"))
  expect_equal(nrow(df), 4L)
  expect_setequal(df$source, c("db", "api_logs", "backups", "third_party_calls"))
  unlink(tmp)
})

test_that("generate_csv_template can write a header-only template", {
  tmp <- tempfile(fileext = ".csv")
  generate_csv_template(tmp, include_examples = FALSE)
  df <- utils::read.csv(tmp, stringsAsFactors = FALSE)
  expect_equal(nrow(df), 0L)
  expect_setequal(names(df), c("source", "item", "provider", "region"))
  unlink(tmp)
})

test_that("a template generated by generate_csv_template round-trips through ingest_csv_inventory", {
  tmp <- tempfile(fileext = ".csv")
  generate_csv_template(tmp)
  configs <- ingest_csv_inventory(tmp)
  expect_setequal(names(configs), c("db", "api_logs", "backups", "third_party_calls"))
  audit <- scan_data_residency(sources = names(configs), configs = configs)
  expect_equal(nrow(audit), 4L)
  unlink(tmp)
})
