## Generates a compliance-ready residency certificate from an audit
## table. Base R only -- writes a plain-text/markdown report rather
## than depending on an external PDF/Excel package, so it can be
## piped into whatever the bank's own doc pipeline needs.

#' Generate a data residency certificate
#'
#' @param audit A data.frame as returned by [scan_data_residency()].
#' @param flagged A data.frame as returned by [flag_offshore_calls()].
#' @param bank_name Character. Name to appear on the certificate.
#' @param output_file Character or NULL. If given, writes the report
#'   to this path as a markdown file. If NULL, only returns the text.
#' @param regulation A list with `citation` and `deadline_text`, as
#'   used by [build_executive_summary()]. Defaults to the CBN 2027
#'   data localization circular; pass a different value to cite a
#'   different rule.
#' @return Invisibly, a character vector of the report lines.
#' @export
gen_residency_certificate <- function(audit, flagged, bank_name,
                                       output_file = NULL,
                                       regulation = .cbn_2027_regulation) {
  .require_license()
  stopifnot(is.data.frame(audit), is.data.frame(flagged))
  stopifnot(is.character(bank_name), length(bank_name) == 1L)

  total <- nrow(audit)
  n_flagged <- nrow(flagged)
  n_local <- sum(audit$jurisdiction == "local")
  pct_local <- if (total > 0) round(100 * n_local / total, 1) else NA

  verdict <- if (total == 0) {
    "UNKNOWN -- no data audited"
  } else if (n_flagged == 0) {
    "COMPLIANT"
  } else {
    "NON-COMPLIANT -- action required"
  }

  by_source <- if (total > 0) {
    tbl <- table(audit$source, audit$jurisdiction)
    as.data.frame.matrix(tbl)
  } else {
    data.frame()
  }

  regulator_label <- if (!is.null(regulation$regulator_name)) regulation$regulator_name else "the relevant regulator"

  lines <- c(
    "# Payment Data Residency Certificate",
    "",
    sprintf("*Independent third-party audit, generated by `residencyR` -- not issued by, endorsed by, or affiliated with %s.*", regulator_label),
    "",
    sprintf("**Institution:** %s", bank_name),
    sprintf("**Generated:** %s", format(Sys.Date(), "%Y-%m-%d")),
    sprintf("**Compliance deadline:** %s", regulation$deadline_text),
    sprintf("**Verdict:** %s", verdict),
    ""
  )

  scan_errors <- attr(audit, "scan_errors")
  if (!is.null(scan_errors)) {
    lines <- c(
      lines,
      "## WARNING: incomplete scan",
      "",
      sprintf(
        "%d source(s) failed to scan and are NOT reflected in this audit. Do not treat this certificate as complete until these are resolved:",
        length(scan_errors)
      ),
      paste0("- ", scan_errors),
      ""
    )
  }

  lines <- c(
    lines,
    build_executive_summary(audit, flagged, regulation),
    "",
    "## Summary",
    "",
    sprintf("- Total data points audited: %d", total),
    sprintf("- Local (Nigeria) resident: %d (%s%%)", n_local, pct_local),
    sprintf("- Flagged for review (offshore/unknown): %d", n_flagged),
    ""
  )

  if (nrow(by_source) > 0) {
    lines <- c(lines, "## Breakdown by source", "")
    src_names <- rownames(by_source)
    for (i in seq_len(nrow(by_source))) {
      row_txt <- paste(
        sprintf("%s: %d", colnames(by_source), unlist(by_source[i, ])),
        collapse = ", "
      )
      lines <- c(lines, sprintf("- **%s** -- %s", src_names[i], row_txt))
    }
    lines <- c(lines, "")
  }

  if (n_flagged > 0) {
    lines <- c(lines, "## Items Requiring Remediation", "")
    for (i in seq_len(nrow(flagged))) {
      lines <- c(
        lines,
        sprintf(
          "%d. [%s] %s -- status: %s (%s, %s)",
          i, flagged$source[i], flagged$item[i], flagged$jurisdiction[i],
          flagged$provider[i], flagged$location[i]
        )
      )
    }
  } else {
    lines <- c(lines, "## Items Requiring Remediation", "", "None. All audited data points are Nigeria-resident.")
  }

  if (!is.null(output_file)) {
    writeLines(lines, con = output_file)
  }

  invisible(lines)
}
